server:
  port: 8801
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka02
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka01:8800/eureka