server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: borrow-service
          uri: lb://borrowservice
          predicates:
            - Path=/borrow/**
          filters:
            - AddRequestHeader=Test, HelloWorld!
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka,http://localhost:8801/eureka